modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=" "
[[mods]]
    modId="solarminecraft"
    version="1.20.1"
    displayName="Solar Minecraft"
    displayURL=" "
    authors="Ella Noyes"
    description='''
    Solar Powered Minecraft
    '''

[[dependencies.solarminecraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solarminecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
